#ifndef GLOBALDEFINITION_H_
#define GLOBALDEFINITION_H_

#define VERSION ("v3.1.2")

#define SERIAL_BAUD_RATE (9600UL)

#define DIGITAL_INPUT_COUNT (16)
#define DIGITAL_OUTPUT_COUNT (8)

#define ANALOG_INPUT_COUNT (4)
#define ANALOG_INPUT_FULL_SCALE (20.0f)
#define ANALOG_INPUT_RESOLUTION (1023.0f)

#define KISAN_ANALOG_INPUT_COUNT (8)
#define KISAN_DIGITAL_OUTPUT_COUNT (8)
#define KISAN_ANALOG_OUTPUT_COUNT (4)
#define KISAN_ANALOG_OUTPUT_MAX_VALUE (20000)

#define KISAN_ADDRESS_KM6015 (1)
#define KISAN_ADDRESS_KM6023 (1)
#define KISAN_ADDRESS_KM6063 (2)

#define KISAN_SEND_BUFFER_SIZE (48)
#define KISAN_PAYLOAD_BUFFER_SIZE (32)
#define KISAN_RECEIVE_BUFFER_SIZE (64)
#define KISAN_RETRY_COUNT (5)
#define KISAN_RECEIVE_TIMEOUT_MILLISECONDS (1000)
#define KISAN_POLL_INTERVAL_MILLISECONDS (500)

#define REMOTE_RECEIVE_BUFFER_SIZE (32)
#define REMOTE_COMMAND_BUFFER_SIZE (8)
#define REMOTE_ARGUMENT_COUNT (8)
#define REMOTE_ARGUMENT_BUFFER_SIZE (8)
#define REMOTE_RESPONSE_BUFFER_SIZE (120)

#define INPUT_CHATTERING_TIMEOUT_MILLISECONDS (100)
#define BUILTIN_LED_INTERVAL_MILLISECONDS (1000)

#define OXYGEN_SENSOR_INPUT_INDEX (2)

#define EMERGENCY_INPUT_INDEX (15)
#define ALARM_OUTPUT_INDEX (5)
#define MAIN_VALVE_OUTPUT_INDEX (0)
#define FAN_FIRST_OUTPUT_INDEX (6)
#define FAN_SECOND_OUTPUT_INDEX (7)

#endif
