#ifndef GLOBALDEFINITION_H_
#define GLOBALDEFINITION_H_

#define VERSION ("v3.0.0")

//#define DEBUG

//#ifdef DEBUG
    //#define DIGITAL_INPUT_FIRST_PIN (22)
    //#define DIGITAL_INPUT_COUNT (16)
    //#define DIGITAL_INPUT_LAST_PIN (DIGITAL_INPUT_FIRST_PIN + DIGITAL_INPUT_COUNT - 1)
//
    //#define DIGITAL_OUTPUT_FIRST_PIN (38)
    //#define DIGITAL_OUTPUT_COUNT (14)
    //#define DIGITAL_OUTPUT_LAST_PIN (DIGITAL_OUTPUT_FIRST_PIN + DIGITAL_OUTPUT_COUNT - 1)
    //#define ANALOG_INPUT_COUNT (4)
//#else
    
//#endif

#define DIGITAL_INPUT_FIRST_PIN (30)
#define DIGITAL_INPUT_COUNT (16)
#define DIGITAL_INPUT_LAST_PIN (DIGITAL_INPUT_FIRST_PIN + DIGITAL_INPUT_COUNT - 1)

#define DIGITAL_OUTPUT_FIRST_PIN (22)
#define DIGITAL_OUTPUT_COUNT (8)
#define DIGITAL_OUTPUT_LAST_PIN (DIGITAL_OUTPUT_FIRST_PIN + DIGITAL_OUTPUT_COUNT - 1)

#define ANALOG_INPUT_COUNT (4)
#define KISAN_ANALOG_INPUT_COUNT (8)
#define KISAN_DIGITAL_OUTPUT_COUNT (8)
#define KISAN_ANALOG_OUTPUT_COUNT (4)

#define KISAN_MODULE_COUNTS (1)

#endif
