set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

file(READ "${CMAKE_CURRENT_LIST_DIR}/../toolchain.lock.json" FAD_TOOLCHAIN_LOCK)
string(JSON FAD_AVR_GCC_DIRECTORY GET "${FAD_TOOLCHAIN_LOCK}" "avr-gcc" "directory")
string(JSON FAD_DEFAULT_TOOLS_ROOT GET "${FAD_TOOLCHAIN_LOCK}" "tools-root")

if(DEFINED ENV{FAD_TOOLS_ROOT})
    set(FAD_TOOLS_ROOT "$ENV{FAD_TOOLS_ROOT}")
else()
    set(FAD_TOOLS_ROOT "$ENV{LOCALAPPDATA}/${FAD_DEFAULT_TOOLS_ROOT}")
endif()

file(TO_CMAKE_PATH "${FAD_TOOLS_ROOT}/${FAD_AVR_GCC_DIRECTORY}" AVR_TOOLCHAIN_ROOT)
set(AVR_TOOLCHAIN_ROOT "${AVR_TOOLCHAIN_ROOT}" CACHE PATH "AVR GCC toolchain root")

if(NOT EXISTS "${AVR_TOOLCHAIN_ROOT}/bin")
    message(FATAL_ERROR "AVR GCC toolchain is missing at ${AVR_TOOLCHAIN_ROOT}. Run: python Scripts/verify.py setup")
endif()

set(CMAKE_EXECUTABLE_SUFFIX_CXX ".elf")
find_program(CMAKE_CXX_COMPILER avr-g++ PATHS "${AVR_TOOLCHAIN_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_AR avr-gcc-ar PATHS "${AVR_TOOLCHAIN_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
find_program(CMAKE_RANLIB avr-gcc-ranlib PATHS "${AVR_TOOLCHAIN_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
find_program(AVR_OBJCOPY avr-objcopy PATHS "${AVR_TOOLCHAIN_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
find_program(AVR_SIZE avr-size PATHS "${AVR_TOOLCHAIN_ROOT}/bin" NO_DEFAULT_PATH REQUIRED)
